=== altaiojok/Battleship/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="configs" type="configs"/>

    <xsd:complexType name="configs">
        <xsd:sequence>
            <xsd:element name="config" type="config" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="config">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="value" type="xsd:string"/>
            <xsd:element name="type" type="type"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="int"/>
            <xsd:enumeration value="boolean"/>
            <xsd:enumeration value="string"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== altaiojok/Battleship/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<configs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="config.xsd">

    <config>
        <name>debugMode</name>
        <value>false</value>
        <type>boolean</type>
    </config>

    <config>
        <name>gridSize</name>
        <value>10</value>
        <type>int</type>
    </config>

</configs>
